services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: rootpassword

  rabbbitmq:
    image: rabbitmq:3.13-management
    ports:
      - 15672:15672
      - 5672:5672